swagger:
  isOpen: false #swagger是否打开


spring:
  kafka:
      bootstrap-servers: 192.168.1.230:9092
      consumer:
        group-id: default-a
        enable-auto-commit: false
        value-deserializer: com.example.config.ObjectDeSerializer
        #earliest提交后的位置开始消费 latest生产者先启动会把多出的消息舍弃
        auto-offset-reset: earliest
      listener:
        concurrency: 10
        ack-mode: manual_immediate


#RECORD
#每处理一条commit一次
#BATCH(默认)
#每次poll的时候批量提交一次，频率取决于每次poll的调用频率
#TIME
#每次间隔ackTime的时间去commit(跟auto commit interval有什么区别呢？)
#COUNT
#累积达到ackCount次的ack去commit
#COUNT_TIME
#ackTime或ackCount哪个条件先满足，就commit
#MANUAL
#listener负责ack，但是背后也是批量上去
#MANUAL_IMMEDIATE
#listner负责ack，每调用一次，就立即commit