
server:
  port: 8082
  servlet:
    context-path: /cmsapi

pay:
  #回掉地址
  notify-url-prefix: http://www.baidu.com${server.servlet.context-path}
  #支付完成后跳转地址
  return-url-prefix: http://www.sina.com

spring:
  redis:
    host: 127.0.0.1
    password: homewell
    port: 6379
    lettuce:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1ms
      shutdown-timeout: 10000ms
    database: 0
    timeout: 60000ms

dubbo:
  application:
    name: base-api
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.example



oss:
  key: 11111
  secret: 1111
  endpoint: oss-cn-shanghai.aliyuncs.com
  defaultBucket: charge-test
